### ISSUE TITLE
I believe this repo should have more stars 

### ISSUE THREAD

**Issue by martin12333** [Haalon/cells#1]
(I am searching, whether, in the future, to develop my rules ... for this online tool or for another online tool)

maybe for discoverability you can add 

website http://haalon.com/cells/

github-topics:
cellular-automata
glsl
game-of-life
online?
javascript

a reddit discussion
https://www.reddit.com/r/cellular_automata/comments/gtxqyq/interactive_and_gpuaccelerated_online_ca/

**Comment by Haalon** [comment]
Thanks for your reply
Ye, more info won't hurt) 

I never expected this project to be something more than my personal CA playground, 
so I didn't consider adding any info
